// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	solaredge "github.com/clambin/solaredge"
)

// PowerGetter is an autogenerated mock type for the PowerGetter type
type PowerGetter struct {
	mock.Mock
}

type PowerGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *PowerGetter) EXPECT() *PowerGetter_Expecter {
	return &PowerGetter_Expecter{mock: &_m.Mock}
}

// GetPowerOverview provides a mock function with given fields: ctx
func (_m *PowerGetter) GetPowerOverview(ctx context.Context) (solaredge.PowerOverview, error) {
	ret := _m.Called(ctx)

	var r0 solaredge.PowerOverview
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (solaredge.PowerOverview, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) solaredge.PowerOverview); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(solaredge.PowerOverview)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PowerGetter_GetPowerOverview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPowerOverview'
type PowerGetter_GetPowerOverview_Call struct {
	*mock.Call
}

// GetPowerOverview is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PowerGetter_Expecter) GetPowerOverview(ctx interface{}) *PowerGetter_GetPowerOverview_Call {
	return &PowerGetter_GetPowerOverview_Call{Call: _e.mock.On("GetPowerOverview", ctx)}
}

func (_c *PowerGetter_GetPowerOverview_Call) Run(run func(ctx context.Context)) *PowerGetter_GetPowerOverview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PowerGetter_GetPowerOverview_Call) Return(_a0 solaredge.PowerOverview, _a1 error) *PowerGetter_GetPowerOverview_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PowerGetter_GetPowerOverview_Call) RunAndReturn(run func(context.Context) (solaredge.PowerOverview, error)) *PowerGetter_GetPowerOverview_Call {
	_c.Call.Return(run)
	return _c
}

// NewPowerGetter creates a new instance of PowerGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPowerGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *PowerGetter {
	mock := &PowerGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
