// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	tado "github.com/clambin/tado"
)

// WeatherGetter is an autogenerated mock type for the WeatherGetter type
type WeatherGetter struct {
	mock.Mock
}

type WeatherGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *WeatherGetter) EXPECT() *WeatherGetter_Expecter {
	return &WeatherGetter_Expecter{mock: &_m.Mock}
}

// GetWeatherInfo provides a mock function with given fields: ctx
func (_m *WeatherGetter) GetWeatherInfo(ctx context.Context) (tado.WeatherInfo, error) {
	ret := _m.Called(ctx)

	var r0 tado.WeatherInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (tado.WeatherInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) tado.WeatherInfo); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(tado.WeatherInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WeatherGetter_GetWeatherInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWeatherInfo'
type WeatherGetter_GetWeatherInfo_Call struct {
	*mock.Call
}

// GetWeatherInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *WeatherGetter_Expecter) GetWeatherInfo(ctx interface{}) *WeatherGetter_GetWeatherInfo_Call {
	return &WeatherGetter_GetWeatherInfo_Call{Call: _e.mock.On("GetWeatherInfo", ctx)}
}

func (_c *WeatherGetter_GetWeatherInfo_Call) Run(run func(ctx context.Context)) *WeatherGetter_GetWeatherInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *WeatherGetter_GetWeatherInfo_Call) Return(_a0 tado.WeatherInfo, _a1 error) *WeatherGetter_GetWeatherInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WeatherGetter_GetWeatherInfo_Call) RunAndReturn(run func(context.Context) (tado.WeatherInfo, error)) *WeatherGetter_GetWeatherInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewWeatherGetter creates a new instance of WeatherGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWeatherGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *WeatherGetter {
	mock := &WeatherGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
