with-expecter: true
filename: "{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/clambin/solaredge-monitor/internal/web:
    interfaces:
      Repository:
      RedisClient:
