with-expecter: true
filename: "{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/clambin/solaredge-monitor/collector/solaredgeScraper:
    interfaces:
      Site:
  github.com/clambin/solaredge-monitor/collector/tadoScraper:
    interfaces:
      API: