// Code generated by mockery v2.50.1. DO NOT EDIT.

package mocks

import (
	context "context"

	redis "github.com/redis/go-redis/v9"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// RedisClient is an autogenerated mock type for the RedisClient type
type RedisClient struct {
	mock.Mock
}

type RedisClient_Expecter struct {
	mock *mock.Mock
}

func (_m *RedisClient) EXPECT() *RedisClient_Expecter {
	return &RedisClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, key
func (_m *RedisClient) Get(ctx context.Context, key string) *redis.StringCmd {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *redis.StringCmd
	if rf, ok := ret.Get(0).(func(context.Context, string) *redis.StringCmd); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.StringCmd)
		}
	}

	return r0
}

// RedisClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type RedisClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *RedisClient_Expecter) Get(ctx interface{}, key interface{}) *RedisClient_Get_Call {
	return &RedisClient_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *RedisClient_Get_Call) Run(run func(ctx context.Context, key string)) *RedisClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RedisClient_Get_Call) Return(_a0 *redis.StringCmd) *RedisClient_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RedisClient_Get_Call) RunAndReturn(run func(context.Context, string) *redis.StringCmd) *RedisClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value, expiration
func (_m *RedisClient) Set(ctx context.Context, key string, value any, expiration time.Duration) *redis.StatusCmd {
	ret := _m.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 *redis.StatusCmd
	if rf, ok := ret.Get(0).(func(context.Context, string, any, time.Duration) *redis.StatusCmd); ok {
		r0 = rf(ctx, key, value, expiration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.StatusCmd)
		}
	}

	return r0
}

// RedisClient_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type RedisClient_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value any
//   - expiration time.Duration
func (_e *RedisClient_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *RedisClient_Set_Call {
	return &RedisClient_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *RedisClient_Set_Call) Run(run func(ctx context.Context, key string, value any, expiration time.Duration)) *RedisClient_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(any), args[3].(time.Duration))
	})
	return _c
}

func (_c *RedisClient_Set_Call) Return(_a0 *redis.StatusCmd) *RedisClient_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RedisClient_Set_Call) RunAndReturn(run func(context.Context, string, any, time.Duration) *redis.StatusCmd) *RedisClient_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewRedisClient creates a new instance of RedisClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedisClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedisClient {
	mock := &RedisClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
