// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	context "context"

	solaredge "github.com/clambin/solaredge"
	mock "github.com/stretchr/testify/mock"
)

// API is an autogenerated mock type for the API type
type API struct {
	mock.Mock
}

// GetPowerOverview provides a mock function with given fields: _a0
func (_m *API) GetPowerOverview(_a0 context.Context) (solaredge.PowerOverview, error) {
	ret := _m.Called(_a0)

	var r0 solaredge.PowerOverview
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (solaredge.PowerOverview, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) solaredge.PowerOverview); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(solaredge.PowerOverview)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAPI interface {
	mock.TestingT
	Cleanup(func())
}

// NewAPI creates a new instance of API. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAPI(t mockConstructorTestingTNewAPI) *API {
	mock := &API{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
