// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	tado "github.com/clambin/tado"
	mock "github.com/stretchr/testify/mock"
)

// API is an autogenerated mock type for the API type
type API struct {
	mock.Mock
}

type API_Expecter struct {
	mock *mock.Mock
}

func (_m *API) EXPECT() *API_Expecter {
	return &API_Expecter{mock: &_m.Mock}
}

// GetWeatherInfo provides a mock function with given fields: ctx
func (_m *API) GetWeatherInfo(ctx context.Context) (tado.WeatherInfo, error) {
	ret := _m.Called(ctx)

	var r0 tado.WeatherInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (tado.WeatherInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) tado.WeatherInfo); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(tado.WeatherInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// API_GetWeatherInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWeatherInfo'
type API_GetWeatherInfo_Call struct {
	*mock.Call
}

// GetWeatherInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *API_Expecter) GetWeatherInfo(ctx interface{}) *API_GetWeatherInfo_Call {
	return &API_GetWeatherInfo_Call{Call: _e.mock.On("GetWeatherInfo", ctx)}
}

func (_c *API_GetWeatherInfo_Call) Run(run func(ctx context.Context)) *API_GetWeatherInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *API_GetWeatherInfo_Call) Return(_a0 tado.WeatherInfo, _a1 error) *API_GetWeatherInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *API_GetWeatherInfo_Call) RunAndReturn(run func(context.Context) (tado.WeatherInfo, error)) *API_GetWeatherInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewAPI creates a new instance of API. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *API {
	mock := &API{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
