name: Build

on:
  push:
    branches:
      - master
      - go123

jobs:
  test:
    uses: ./.github/workflows/test-reuse.yaml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs: [test]
    uses: clambin/workflows/.github/workflows/build.yaml@go1.23
    with:
      image: ghcr.io/clambin/solaredge
