name: Build

on:
  push:
    branches:
      - master
      - pollers

permissions:
  packages: write

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs: [test]
    uses: clambin/workflows/.github/workflows/build.yaml@main
    with:
      image: ghcr.io/clambin/solaredge
      dockerfile: Dockerfile
