name: Build

on:
  push:
    branches:
      - master
      - logging

jobs:
  test:
    uses: ./.github/workflows/test-reuse.yaml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs: [test]
    uses: clambin/workflows/.github/workflows/build.yaml@docker
    with:
      image: ghcr.io/clambin/solaredge

